
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"mrkumar1148@gmail.com",
    "password":"12345678"
}

###

# GET http://localhost:5000/api/auth/all
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjEzM2ZlYWEwOGU1YmVjOTM3MjdlZSIsImVtYWlsIjoibXJrdW1hcjExNDhAZ21haWwuY29tIiwiaWF0IjoxNzUxMjAwNzc3LCJleHAiOjE3NTEyMDE2Nzd9.oaBwLHUW0fwzVcrQeG4cMawbsRCwEoGqSJVY_CpB7b0
###

### Register Worker
### Register Worker


POST http://localhost:5000/api/auth/worker/register
Content-Type: application/json

{
  "email": "mrkumar1148@gmail.com",
  "firstname": "J Kumar",
  "lastname": "Gubbala",
  "username": "jayakumar",
  "password": "12345678",
  "services": ["Electrician"]
}

###


# PUT http://localhost:5000/api/auth/profileupdate
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjExNmIxMjQzNGMzNDdkMzZlOTY1YSIsImVtYWlsIjoiamF5YWswNzc2QGdtYWlsLmNvbSIsImlhdCI6MTc1MTE5MzMxMywiZXhwIjoxNzUxMTk0MjEzfQ.kq3GMIhXb5d_AkedSMQ_Q_8Qu3a5vJWJpkWC2_-g8qM
# Content-Type: application/json

# {
#   "service": ["Electrician", "Plumber"],
#   "skills": ["Wiring", "Leak Fixing", "Circuit Testing"],
#   "phone": "9876543210",
#   "location": "Visakhapatnam"
# }


# POST http://localhost:5000/api/auth/sendresetcode
# Content-Type: application/json

# {
#   "email": "mrkumar1148@gmail.com"
# }

Post http://localhost:5000/api/auth/verifyresetcode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjEzM2ZlYWEwOGU1YmVjOTM3MjdlZSIsImVtYWlsIjoibXJrdW1hcjExNDhAZ21haWwuY29tIiwiaWF0IjoxNzUxMjAwNzc3LCJleHAiOjE3NTEyMDE2Nzd9.oaBwLHUW0fwzVcrQeG4cMawbsRCwEoGqSJVY_CpB7b0
Content-Type: application/json

{
  "email": "mrkumar1148@gmail.com",
  "code": "536956",
  "newPassword": "NewStrongPassword123"
}

###
POST http://localhost:5000/api/auth/customer/register
Content-Type: application/json

{
  "email": "jayakumar.gubbala@gmail.com",
  "firstname": "Jaya",
  "lastname": "Kumar",
  "username": "Jaya",
  "password": "123456"
}

### Customer Login
POST http://localhost:5000/api/auth/customer/login
Content-Type: application/json

{
  "email": "jayakumar.gubbala@gmail.com",
  "password": "Jayak@234"
}


###
PUT http://localhost:5000/api/auth/customer/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjE2ZTkzYWI4Njg4MGI5ZmNlMjAzYyIsImVtYWlsIjoiamF5YWt1bWFyLmd1YmJhbGFAZ21haWwuY29tIiwiaWF0IjoxNzUxMjc1MzUzLCJleHAiOjE3NTEyNzYyNTN9.sUdzVF8Z3OojMguecwZVgWgDT5NUiLXQODJmIA6Y_V4
Content-Type: application/json

{
 "phone":"8919753805",
 "location":"Hyberabad"
}

###
POST http://localhost:5000/api/auth/customer/getcustomer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjE2ZTkzYWI4Njg4MGI5ZmNlMjAzYyIsImVtYWlsIjoiamF5YWt1bWFyLmd1YmJhbGFAZ21haWwuY29tIiwiaWF0IjoxNzUxMjE1Nzk4LCJleHAiOjE3NTEyMTY2OTh9.AhrY1lFu-lHc9j2w4Zxl9CJ-lHpKO0bVxawBhc3CR9o
Content-Type: application/json

{
  "email":"customer1@example.com"
}

###
POST http://localhost:5000/api/auth/customer/sendresetcode
Content-Type: application/json

{
  "email": "jayakumar.gubbala@gmail.com"
}


###
Post http://localhost:5000/api/auth/customer/verifyresetcode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjE2ZTkzYWI4Njg4MGI5ZmNlMjAzYyIsImVtYWlsIjoiamF5YWt1bWFyLmd1YmJhbGFAZ21haWwuY29tIiwiaWF0IjoxNzUxMjE1Nzk4LCJleHAiOjE3NTEyMTY2OTh9.AhrY1lFu-lHc9j2w4Zxl9CJ-lHpKO0bVxawBhc3CR9o
Content-Type: application/json

{
  "email": "jayakumar.gubbala@gmail.com",
  "code": "700897",
  "newPassword": "NewStrongPassword123"
}
###

PUT  http://localhost:5000/api/auth/updateWorkerProfile
Content-Type: application/json

{
  "email": "mrkumar1148@gmail.com",
  "firstname": "J Kumar",
  "lastname": "Gubbala",
  "username": "jayakumar",
  "password": "12345678",
  "services": ["Electrician"]
}

















// WORKER-CUSTOMER REQUEST APIS
###
POST http://localhost:5000/api/auth/workreq
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjE2ZTkzYWI4Njg4MGI5ZmNlMjAzYyIsImVtYWlsIjoiamF5YWt1bWFyLmd1YmJhbGFAZ21haWwuY29tIiwiaWF0IjoxNzUxNjAyMTY5LCJleHAiOjE3NTE2MDM5Njl9.qBII1gNqZpAFMULHB5XAW5j44EfGIltmPa9rgRDUsog
Content-Type: application/json

{
  "customerEmail":"jayakumar.gubbala@gmail.com",
  "customerFirstName":"G Jaya",
  "customerLastName":"Kumar",
  "phoneNumber":"8919753805",
  "location":"Rjyk",
  "serviceWanted":"Car Mech",
  "workerEmail":"mrkumar1148@gmail.com",
  "workerFirstName":"Jaya Kumar",
  "workerLastName":"Gubbala"
}


// GET ALL PARTICULAR WORKER DETAILS
###
GET http://localhost:5000/api/auth/getallwork
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjIxMzIxNTg3ZTFmNmZkYzA3ZThjNSIsImVtYWlsIjoibXJrdW1hcjExNDhAZ21haWwuY29tIiwiaWF0IjoxNzUxMzAzNTU3LCJleHAiOjE3NTEzMDQ0NTd9.aNDRyUbkzDkCUIu5-0yihDrnSGRnhpEspPlg6hLR_jM


###
GET http://localhost:5000/api/auth/getall


// ACCEPT REQUEST API BY WORKER
###
PUT http://localhost:5000/api/auth/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjIxMzIxNTg3ZTFmNmZkYzA3ZThjNSIsImVtYWlsIjoibXJrdW1hcjExNDhAZ21haWwuY29tIiwiaWF0IjoxNzUxMzAzOTYxLCJleHAiOjE3NTEzMDQ4NjF9._yzgKMZe1nbMYErBaBXEpqm3AAuLXSahz0X-Um17Ndw
Content-Type: application/json

{
  "requestId": "6862c56c34c454b6254fbebf",
  "workerStatus": "accepted"
}

